/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ceyhunataykan.view;

import com.ceyhunataykan.controller.KategoriController;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author gulataykan
 */
public class KategoriIslemleri extends javax.swing.JFrame {

    /**
     * Creates new form Kategoriler
     */
    public KategoriIslemleri() {
        initComponents();
        setLocationRelativeTo(null);
        basla();
    }

    public void basla() {
        // Basla fonksiyonuyla buton ikonları ve ilk açılışta kategori tablosu ayarlanıyor.
        btn_ekle.setIcon(new ImageIcon(getClass().getClassLoader().getResource("plussmall.png")));
        btn_guncelle.setIcon(new ImageIcon(getClass().getClassLoader().getResource("refresh.png")));
        btn_sil.setIcon(new ImageIcon(getClass().getClassLoader().getResource("crosssmall.png")));
        tabloDoldur();
    }

    public void tabloDoldur(){
        // Tablo doldurma işlemi yapılıyor. İlk sutun gizleniyor.
        tbl_kategoriler.setRowHeight(30);
        tbl_kategoriler.setModel(KategoriController.kategoriGetir());
        tbl_kategoriler.getColumnModel().getColumn(0).setMinWidth(0);
        tbl_kategoriler.getColumnModel().getColumn(0).setMaxWidth(0);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_ekle = new javax.swing.JButton();
        txt_kategori = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_guncelle = new javax.swing.JButton();
        btn_sil = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_kategoriler = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbl_kategori_id = new javax.swing.JLabel();

        setTitle("Kategoriler");

        btn_ekle.setText("Ekle");
        btn_ekle.setMaximumSize(new java.awt.Dimension(76, 22));
        btn_ekle.setMinimumSize(new java.awt.Dimension(76, 22));
        btn_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ekleActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Kategori Adı ");

        btn_guncelle.setText("Güncelle");
        btn_guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guncelleActionPerformed(evt);
            }
        });

        btn_sil.setText("Sil");
        btn_sil.setMaximumSize(new java.awt.Dimension(76, 22));
        btn_sil.setMinimumSize(new java.awt.Dimension(76, 22));
        btn_sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_silActionPerformed(evt);
            }
        });

        tbl_kategoriler.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {}
            },
            new String [] {

            }
        ));
        tbl_kategoriler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_kategorilerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_kategoriler);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Kategoriler");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addContainerGap())
        );

        lbl_kategori_id.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_kategori_id)
                        .addGap(33, 33, 33))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_kategori, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_ekle, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_guncelle, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_sil, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lbl_kategori_id)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_kategori, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_ekle, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_guncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_sil, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ekleActionPerformed
        // Kontrollerden gelen veriler veritabanına ekleniyor.
        try {
            KategoriController.kategoriEkle(txt_kategori.getText());
            JOptionPane.showMessageDialog(null, "Yeni kategori başarıyla eklendi.");
            txt_kategori.setText("");
            tabloDoldur();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Bir hata oluştu. Tekrar deneyiniz.", "Hata", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_ekleActionPerformed

    private void btn_guncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guncelleActionPerformed
        // İlgili kontrolün boş olup olmadığı kontrol ediliyor.
        if (txt_kategori.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Güncelleme yapabilmek için listeden bir kayıt seçiniz.", "Bilgi", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        // Confirmdialog ile onaya göre bilgileri veritabanında güncelliyor.
        int secim = JOptionPane.showConfirmDialog(null, "Seçilen kategoriyi güncellemek istiyormusunuz?", "Uyarı", JOptionPane.WARNING_MESSAGE);
        if (secim == JOptionPane.YES_OPTION) {
            try {
                KategoriController.kategoriGuncelle(Integer.valueOf(lbl_kategori_id.getText()), txt_kategori.getText());
                JOptionPane.showMessageDialog(null, "Kategori başarıyla güncellendi.");
                txt_kategori.setText("");
                tabloDoldur();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Bir hata oluştu. Tekrar deneyiniz.", "Hata", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_guncelleActionPerformed

    private void tbl_kategorilerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_kategorilerMouseClicked
        // Tabloda ilgili satır seçildiğinde ilgili verileri kontrollere aktarılıyor.
        lbl_kategori_id.setText(String.valueOf(tbl_kategoriler.getModel().getValueAt(tbl_kategoriler.getSelectedRow(), 0)));
        txt_kategori.setText(String.valueOf(tbl_kategoriler.getModel().getValueAt(tbl_kategoriler.getSelectedRow(), 1)));
    }//GEN-LAST:event_tbl_kategorilerMouseClicked

    private void btn_silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_silActionPerformed
        // İlgili kontrolün boş olup olmadığı kontrol ediliyor.
        if (txt_kategori.getText().equals("")) {
            JOptionPane.showConfirmDialog(null, "Silme yapabilmek için listeden bir kayıt seçiniz.", "Bilgi", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        // Confirmdialog ile onaya göre bilgileri veritabanında siliniyor.
        int secim = JOptionPane.showConfirmDialog(null, "Seçilen kategoriyi silmek istiyormusunuz?", "Uyarı", JOptionPane.WARNING_MESSAGE);
        if (secim == JOptionPane.YES_OPTION) {
            try {
                KategoriController.kategoriSil(Integer.valueOf(lbl_kategori_id.getText()));
                JOptionPane.showMessageDialog(null, "Kategori başarıyla silindi.");
                txt_kategori.setText("");
                tabloDoldur();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Bir hata oluştu. Tekrar deneyiniz.", "Hata", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_silActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KategoriIslemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KategoriIslemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KategoriIslemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            //java.util.lotbl_kategorilerogger.getLogger(Kategoriler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KategoriIslemleri().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ekle;
    private javax.swing.JButton btn_guncelle;
    private javax.swing.JButton btn_sil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_kategori_id;
    private javax.swing.JTable tbl_kategoriler;
    private javax.swing.JTextField txt_kategori;
    // End of variables declaration//GEN-END:variables
}
