/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ceyhunataykan.view;

import com.ceyhunataykan.controller.FisController;
import com.ceyhunataykan.controller.KullaniciController;
import com.ceyhunataykan.controller.MevcutKullanici;
import com.ceyhunataykan.controller.SatisController;
import com.ceyhunataykan.controller.UrunController;
import com.ceyhunataykan.model.Fisler;
import com.ceyhunataykan.model.Kullanicilar;
import com.ceyhunataykan.model.Urunler;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gulataykan
 */
public class SatisIslemleri extends javax.swing.JFrame {

    // Sayıların formatlı bir biçimde yazılması için DeCimalFormat sınıfını kullanıyoruz.
    DecimalFormat df = new DecimalFormat("#0.00");
    private Double toplamTutar = 0.00;
    private String odemeTipi = "";

    /**
     * Creates new form SatisYap
     */
    public SatisIslemleri() {
        initComponents();
        setLocationRelativeTo(null);
        basla();
    }

    public void basla() {
        // Buton ikonları ayarlanıyor.
        btn_odemeAl.setIcon(new ImageIcon(getClass().getClassLoader().getResource("tick.png")));
        btn_iptal.setIcon(new ImageIcon(getClass().getClassLoader().getResource("cross.png")));
        btn_sepetEkle.setIcon(new ImageIcon(getClass().getClassLoader().getResource("plus.png")));
        btn_sepetCikar.setIcon(new ImageIcon(getClass().getClassLoader().getResource("minus.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grp_odemeTipi = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_sepet = new javax.swing.JTable();
        btn_sepetEkle = new javax.swing.JButton();
        txt_adet = new javax.swing.JTextField();
        lbl_adet = new javax.swing.JLabel();
        txt_urunBarkod = new javax.swing.JTextField();
        lbl_urunBarkod = new javax.swing.JLabel();
        lbl_tutar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbl_toplamTutar = new javax.swing.JLabel();
        btn_iptal = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btn_odemeAl = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        rdb_nakit = new javax.swing.JRadioButton();
        rdb_kredi = new javax.swing.JRadioButton();
        rdb_indirim = new javax.swing.JRadioButton();
        btn_sepetCikar = new javax.swing.JButton();

        setTitle("Alışveriş Sepeti");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tbl_sepet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Barkod", "Urun Adı", "Adet", "Birim Fiyat", "Toplam Fiyat"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_sepet);
        if (tbl_sepet.getColumnModel().getColumnCount() > 0) {
            tbl_sepet.getColumnModel().getColumn(3).setResizable(false);
            tbl_sepet.getColumnModel().getColumn(4).setResizable(false);
        }

        btn_sepetEkle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_sepetEkle.setText("Sepete Ekle");
        btn_sepetEkle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_sepetEkle.setIconTextGap(25);
        btn_sepetEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sepetEkleActionPerformed(evt);
            }
        });

        txt_adet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_adetKeyPressed(evt);
            }
        });

        lbl_adet.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_adet.setText("Adet");

        txt_urunBarkod.setBackground(new java.awt.Color(102, 255, 204));
        txt_urunBarkod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_urunBarkodKeyPressed(evt);
            }
        });

        lbl_urunBarkod.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_urunBarkod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code.png"))); // NOI18N
        lbl_urunBarkod.setText("Ürün Barkod");

        lbl_tutar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_tutar.setText("Toplam Ödenecek Tutar");

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_toplamTutar.setBackground(new java.awt.Color(51, 51, 51));
        lbl_toplamTutar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbl_toplamTutar.setForeground(new java.awt.Color(0, 204, 0));
        lbl_toplamTutar.setText("0.00 TL");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_toplamTutar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_toplamTutar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        btn_iptal.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btn_iptal.setText("İptal");
        btn_iptal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_iptal.setIconTextGap(25);
        btn_iptal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iptalActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Alışveriş Sepeti");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addContainerGap())
        );

        btn_odemeAl.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btn_odemeAl.setText("Ödeme Al");
        btn_odemeAl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_odemeAl.setIconTextGap(25);
        btn_odemeAl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_odemeAlActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ödeme Tipi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        grp_odemeTipi.add(rdb_nakit);
        rdb_nakit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdb_nakit.setText("Nakit");

        grp_odemeTipi.add(rdb_kredi);
        rdb_kredi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdb_kredi.setText("Kredi Kartı");

        grp_odemeTipi.add(rdb_indirim);
        rdb_indirim.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdb_indirim.setText("İndirim Kartı");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdb_nakit)
                    .addComponent(rdb_kredi)
                    .addComponent(rdb_indirim))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdb_nakit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdb_kredi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdb_indirim)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        btn_sepetCikar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_sepetCikar.setText("Çıkar");
        btn_sepetCikar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_sepetCikar.setIconTextGap(25);
        btn_sepetCikar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sepetCikarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_adet)
                    .addComponent(txt_urunBarkod)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_iptal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_odemeAl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_urunBarkod)
                            .addComponent(lbl_adet)
                            .addComponent(lbl_tutar)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_sepetEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_sepetCikar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_urunBarkod)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_urunBarkod, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_adet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_adet, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_sepetEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_sepetCikar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_tutar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_odemeAl, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_iptal, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sepetEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sepetEkleActionPerformed
        if (txt_urunBarkod.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Lütfen Barkod Giriniz!", "Bilgi", JOptionPane.INFORMATION_MESSAGE);
        } else if (txt_adet.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Lütfen Ürün Adedi Giriniz!", "Bilgi", JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                // Barkod kontrolünde gelen veri ile ilgili ürünün id'si bulunuyor.
                int id = UrunController.urunIdBul(txt_urunBarkod.getText());
                // Id'si bulunan ürünün verileri veritabanından çekiliyor ve entity'e ekleniyor.
                Urunler urun = UrunController.urunBul(id);

                // Mevcut tablonun modeli yeni Tablo modeline ekleniyor.
                DefaultTableModel tm = (DefaultTableModel) tbl_sepet.getModel();
                // Gelen veriler tablonun ilgili alanlarına ekleniyor.
                tm.addRow(new Object[]{
                    urun.getUrun_barkod(),
                    urun.getUrun_adi(),
                    txt_adet.getText(),
                    (float) urun.getUrun_satis(),
                    (float) urun.getUrun_satis() * Integer.parseInt(txt_adet.getText())
                });

                // Eklenen ürünlerin fiyatı toplanıyor.
                toplamTutar += ((float) urun.getUrun_satis() * Integer.parseInt(txt_adet.getText()));
                lbl_toplamTutar.setText(String.valueOf(df.format(toplamTutar)) + " TL");
                txt_urunBarkod.setText("");
                txt_adet.setText("");
            } catch (Exception e) {
                // Ürün bilgisi bulunamadığı zaman kullanıcıya uyarı bilgisi veriliyor.
                JOptionPane.showMessageDialog(null, "Ürün bulunamadı.");
            }
        }
    }//GEN-LAST:event_btn_sepetEkleActionPerformed

    private void btn_sepetCikarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sepetCikarActionPerformed
        // Tablodan ürün çıkarıldığında tablo ve toplam tutar verisi güncelleniyor.
        DefaultTableModel tm = (DefaultTableModel) tbl_sepet.getModel();
        tbl_sepet.setRowHeight(30);
        float son = (float) tbl_sepet.getValueAt(tm.getRowCount() - 1, 4);
        toplamTutar -= son;
        lbl_toplamTutar.setText(df.format(toplamTutar) + " TL");
        // İlgili ürün tablodan çıkarılıyor.
        tm.removeRow(tm.getRowCount() - 1);
    }//GEN-LAST:event_btn_sepetCikarActionPerformed

    private void btn_odemeAlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_odemeAlActionPerformed
        if(tbl_sepet.getRowCount() <= 0 ){
            JOptionPane.showMessageDialog(null, "Lütfen sepete ürün ekleyin!", "Bilgi", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        // Öncelikli olarak ödeme tipi seçilmiş mi kontrol ediliyor.
        if (rdb_nakit.isSelected()) {
            odemeTipi = rdb_nakit.getText();
        } else if (rdb_kredi.isSelected()) {
            odemeTipi = rdb_kredi.getText();
        } else if (rdb_indirim.isSelected()) {
            odemeTipi = rdb_indirim.getText();
        } else {
            JOptionPane.showMessageDialog(null, "Lütfen Ödeme Tipini Seçiniz");
            return;
        }

        // Confirm dialog onayına göre öncelikle fis oluşturuluyor, ardından tablodaki satılan ürünler dişe ekleniyor.
        int onay = JOptionPane.showConfirmDialog(null, "Sepeti Onaylıyormusunuz?", "Onay", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if (onay == JOptionPane.YES_OPTION) {
            try {
                // Fiş oluşturuluyor.
                Fisler fis = new Fisler();
                fis.setFis_odeme_tur(odemeTipi);
                fis.setFis_tarih(new Date());
                FisController.fisEkle(fis);
                // Son fiş veritabanından bulunuyor.
                Fisler sonFis = FisController.fisBul();
                Kullanicilar kullanici = KullaniciController.kullaniciBul(MevcutKullanici.id);
                DefaultTableModel tm = (DefaultTableModel) tbl_sepet.getModel();
                double toplamFiyat = 0.00;
                // Sepetteki ürünler satış olarak kaydediliyor. Bulunan son fiste ekleniyor.
                for (int i = 0; i < tbl_sepet.getRowCount(); i++) {
                    int id = UrunController.urunIdBul(String.valueOf(tbl_sepet.getValueAt(i, 0)));
                    Urunler urun = UrunController.urunBul(id);
                    toplamFiyat += (Integer.parseInt(tbl_sepet.getValueAt(i, 2).toString()) * urun.getUrun_satis());
                    SatisController.satisEkle(
                            Integer.parseInt(tbl_sepet.getValueAt(i, 2).toString()),
                            urun.getUrun_satis(),
                            (float) Integer.parseInt(tbl_sepet.getValueAt(i, 2).toString()) * urun.getUrun_satis(),
                            urun,
                            new Date(),
                            sonFis,
                            kullanici
                    );
                    // Satıştaki ürünlerin stokta adetleri güncelleniyor.
                    UrunController.urunAdetGuncelle(urun.getUrun_id(), urun.getUrun_adet() - Integer.parseInt(tbl_sepet.getValueAt(i, 2).toString()));
                }

                // Veritabanındaki fis tablosu güncenlleniyor.
                FisController.fisGuncelle(sonFis.getFis_id(), toplamFiyat);
                JOptionPane.showMessageDialog(null, "Ödeme Alındı.");

                txt_urunBarkod.setText("");
                txt_adet.setText("");
                lbl_toplamTutar.setText("0.00 TL");
                tabloTemizle();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Bir hata oluştu. Tekrar deneyiniz.", "Hata", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_odemeAlActionPerformed

    // Tabloyu temizlemek için kullandığımız fonksiyon.
    public void tabloTemizle() {
        DefaultTableModel tm = (DefaultTableModel) tbl_sepet.getModel();
        int rowCount = tm.getRowCount();
        // Satırlar tek tek siliniyor.
        for (int i = rowCount - 1; i >= 0; i--) {
            tm.removeRow(i);
        }
    }

    private void txt_adetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_adetKeyPressed
        // Adet kontrolünde sadece sayı girilmesi için gerekli kontroller yapılıyor.
        String value = txt_adet.getText();
        int l = value.length();
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || (evt.getKeyChar() == KeyEvent.VK_BACK_SPACE) || (evt.getKeyChar() == KeyEvent.VK_DELETE)) {
            txt_adet.setEditable(true);
        } else {
            txt_adet.setEditable(false);
        }
    }//GEN-LAST:event_txt_adetKeyPressed

    private void txt_urunBarkodKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_urunBarkodKeyPressed
        // Barkod bilgisi girildikten sonra klavyeden enter tuşuna basılında tabloya otomatik ekliyor.
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            // Barkod kontrolünde gelen veri ile ilgili ürünün id'si bulunuyor.
            int id = UrunController.urunIdBul(txt_urunBarkod.getText());
            // Id'si bulunan ürünün verileri veritabanından çekiliyor ve entity'e ekleniyor.
            Urunler urun = UrunController.urunBul(id);
            // Ürün bilgisi bulunamadığı zaman kullanıcıya uyarı bilgisi veriliyor.
            if (urun == null) {
                JOptionPane.showMessageDialog(null, "Ürün bulunamadı.");
                return;
            }
            // Mevcut tablonun modeli yeni Tablo modeline ekleniyor.
            DefaultTableModel tm = (DefaultTableModel) tbl_sepet.getModel();

            // Gelen veriler tablonun ilgili alanlarına ekleniyor.
            tm.addRow(new Object[]{
                urun.getUrun_barkod(),
                urun.getUrun_adi(),
                "1",
                (float) urun.getUrun_satis(),
                (float) urun.getUrun_satis() * 1
            });

            // Eklenen ürünlerin fiyatı toplanıyor.
            toplamTutar += ((float) urun.getUrun_satis() * 1);
            lbl_toplamTutar.setText(String.valueOf(df.format(toplamTutar)) + " TL");
            txt_urunBarkod.setText("");
        }
    }//GEN-LAST:event_txt_urunBarkodKeyPressed

    private void btn_iptalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iptalActionPerformed
        int onay = JOptionPane.showConfirmDialog(null, "Sepeti İptal Ediyormusunuz?", "Sepet İptal", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if (onay == JOptionPane.YES_OPTION) {
            tabloTemizle();
            lbl_toplamTutar.setText("0.00 TL");
        }
    }//GEN-LAST:event_btn_iptalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SatisIslemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SatisIslemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SatisIslemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SatisIslemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SatisIslemleri().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_iptal;
    private javax.swing.JButton btn_odemeAl;
    private javax.swing.JButton btn_sepetCikar;
    private javax.swing.JButton btn_sepetEkle;
    private javax.swing.ButtonGroup grp_odemeTipi;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_adet;
    private javax.swing.JLabel lbl_toplamTutar;
    private javax.swing.JLabel lbl_tutar;
    private javax.swing.JLabel lbl_urunBarkod;
    private javax.swing.JRadioButton rdb_indirim;
    private javax.swing.JRadioButton rdb_kredi;
    private javax.swing.JRadioButton rdb_nakit;
    private javax.swing.JTable tbl_sepet;
    private javax.swing.JTextField txt_adet;
    private javax.swing.JTextField txt_urunBarkod;
    // End of variables declaration//GEN-END:variables
}
