/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ceyhunataykan.view;

import com.ceyhunataykan.controller.KategoriController;
import com.ceyhunataykan.controller.MarkaController;
import com.ceyhunataykan.controller.UrunController;
import com.ceyhunataykan.model.Kategoriler;
import com.ceyhunataykan.model.Markalar;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author gulataykan
 */
public class UrunIslemleri extends javax.swing.JFrame {

    /**
     * Creates new form UrunIslemleri
     */
    public UrunIslemleri() {
        initComponents();
        setLocationRelativeTo(null);
        basla();
    }

    public void basla() {
        // Urunler formunun başlangıç ayarları yapılıyor. Kategori ve Marka ID'leri tablo üzerinden gelen veriyi tutmak için 2 adet label kullanıyoruz.
        lbl_kategoriId.setVisible(false);
        lbl_markaId.setVisible(false);
        // Buton ikonları ayarlanıyor.
        btn_ekle.setIcon(new ImageIcon(getClass().getClassLoader().getResource("plussmall.png")));
        btn_guncelle.setIcon(new ImageIcon(getClass().getClassLoader().getResource("refresh.png")));
        btn_sil.setIcon(new ImageIcon(getClass().getClassLoader().getResource("crosssmall.png")));
        tabloDoldur();

        // Marka listesi veritabanından çekiliyor.
        List<Markalar> marka = MarkaController.markaListe();
        // Marka verileri combobox'a yükleniyor. 
        for (com.ceyhunataykan.model.Markalar m : marka) {
            cmb_marka.addItem(m.getMarka_adi());
        }
        // Kategori listesi veritabanından çekiliyor.
        List<Kategoriler> kategori = KategoriController.kategoriListe();
        // Kategori verileri combobox'a yükleniyor.
        for (Kategoriler k : kategori) {
            cmb_kategori.addItem(k.getKategori_adi());
        }

    }

    public void tabloDoldur() {
        // Tablo ayarları yapılıyor. Ürün verileri getiriiyor. İlk satır gizleniyor.
        tbl_urunler.setRowHeight(30);
        tbl_urunler.setModel(UrunController.urunGetir());
        tbl_urunler.getColumnModel().getColumn(0).setMinWidth(0);
        tbl_urunler.getColumnModel().getColumn(0).setMaxWidth(0);
    }

    public void temizle() {
        // Kontrol temizleme
        txt_urunBarkod.setText("");
        txt_urunAdi.setText("");
        txt_alisFiyat.setText("");
        txt_satisFiyat.setText("");
        txt_stokAdet.setText("");
        txt_kdv.setText("");
        txt_stokAdet.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_arka = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_urunler = new javax.swing.JTable();
        pnl_header = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        pnl_urunBilgileri = new javax.swing.JPanel();
        lbl_urunBarkod = new javax.swing.JLabel();
        txt_urunBarkod = new javax.swing.JTextField();
        lbl_urunAdi = new javax.swing.JLabel();
        txt_urunAdi = new javax.swing.JTextField();
        txt_alisFiyat = new javax.swing.JTextField();
        lbl_alisFiyat = new javax.swing.JLabel();
        txt_stokAdet = new javax.swing.JTextField();
        lbl_stokAdet = new javax.swing.JLabel();
        txt_satisFiyat = new javax.swing.JTextField();
        lbl_satisFiyat = new javax.swing.JLabel();
        lbl_kdv = new javax.swing.JLabel();
        txt_kdv = new javax.swing.JTextField();
        cmb_marka = new javax.swing.JComboBox<>();
        lbl_marka = new javax.swing.JLabel();
        cmb_kategori = new javax.swing.JComboBox<>();
        lbl_kategori = new javax.swing.JLabel();
        lbl_kategoriId = new javax.swing.JLabel();
        lbl_markaId = new javax.swing.JLabel();
        pnl_buton = new javax.swing.JPanel();
        btn_ekle = new javax.swing.JButton();
        btn_guncelle = new javax.swing.JButton();
        btn_sil = new javax.swing.JButton();
        lbl_urunId = new javax.swing.JLabel();

        setTitle("Ürün İşlemleri");
        setResizable(false);

        pnl_arka.setBackground(new java.awt.Color(255, 255, 255));

        tbl_urunler.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbl_urunler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_urunlerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_urunler);

        pnl_header.setBackground(new java.awt.Color(51, 51, 51));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Ürün Tanımlama ve Stok Durumu");

        javax.swing.GroupLayout pnl_headerLayout = new javax.swing.GroupLayout(pnl_header);
        pnl_header.setLayout(pnl_headerLayout);
        pnl_headerLayout.setHorizontalGroup(
            pnl_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_headerLayout.setVerticalGroup(
            pnl_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnl_urunBilgileri.setBackground(new java.awt.Color(255, 255, 255));

        lbl_urunBarkod.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_urunBarkod.setText("Ürün Barkod :");

        lbl_urunAdi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_urunAdi.setText("Ürün Adı :");

        txt_alisFiyat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_alisFiyatKeyPressed(evt);
            }
        });

        lbl_alisFiyat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_alisFiyat.setText("Ürün Alış Fiyatı :");

        txt_stokAdet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_stokAdetKeyPressed(evt);
            }
        });

        lbl_stokAdet.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_stokAdet.setText("Ürün Stok Adet :");

        txt_satisFiyat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_satisFiyatKeyPressed(evt);
            }
        });

        lbl_satisFiyat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_satisFiyat.setText("Ürün Satış Fiyatı :");

        lbl_kdv.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_kdv.setText("% KDV");

        txt_kdv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_kdvKeyPressed(evt);
            }
        });

        cmb_marka.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_markaİtemStateChanged(evt);
            }
        });

        lbl_marka.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_marka.setText("Marka");

        cmb_kategori.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_kategoriİtemStateChanged(evt);
            }
        });

        lbl_kategori.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_kategori.setText("Kategori");

        lbl_kategoriId.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_kategoriId.setForeground(new java.awt.Color(255, 255, 255));
        lbl_kategoriId.setText("id");

        lbl_markaId.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_markaId.setForeground(new java.awt.Color(255, 255, 255));
        lbl_markaId.setText("id");

        javax.swing.GroupLayout pnl_urunBilgileriLayout = new javax.swing.GroupLayout(pnl_urunBilgileri);
        pnl_urunBilgileri.setLayout(pnl_urunBilgileriLayout);
        pnl_urunBilgileriLayout.setHorizontalGroup(
            pnl_urunBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_urunBilgileriLayout.createSequentialGroup()
                .addContainerGap(746, Short.MAX_VALUE)
                .addGroup(pnl_urunBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_markaId)
                    .addComponent(lbl_kategoriId))
                .addContainerGap())
            .addGroup(pnl_urunBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_urunBilgileriLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(pnl_urunBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbl_urunBarkod)
                        .addComponent(txt_urunBarkod, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                        .addComponent(lbl_urunAdi)
                        .addComponent(txt_urunAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(pnl_urunBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnl_urunBilgileriLayout.createSequentialGroup()
                            .addGroup(pnl_urunBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_alisFiyat)
                                .addComponent(txt_alisFiyat, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(pnl_urunBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_kdv)
                                .addComponent(txt_kdv, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(pnl_urunBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_marka)
                                .addComponent(cmb_marka, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(pnl_urunBilgileriLayout.createSequentialGroup()
                            .addGroup(pnl_urunBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_stokAdet)
                                .addComponent(txt_stokAdet, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(pnl_urunBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_satisFiyat, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_satisFiyat))
                            .addGap(18, 18, 18)
                            .addGroup(pnl_urunBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_kategori)
                                .addComponent(cmb_kategori, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnl_urunBilgileriLayout.setVerticalGroup(
            pnl_urunBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_urunBilgileriLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_kategoriId)
                .addGap(41, 41, 41)
                .addComponent(lbl_markaId)
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(pnl_urunBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_urunBilgileriLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(pnl_urunBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnl_urunBilgileriLayout.createSequentialGroup()
                            .addComponent(lbl_stokAdet)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_stokAdet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(pnl_urunBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(pnl_urunBilgileriLayout.createSequentialGroup()
                                    .addComponent(lbl_urunAdi)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_urunAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnl_urunBilgileriLayout.createSequentialGroup()
                                    .addComponent(lbl_alisFiyat)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_alisFiyat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnl_urunBilgileriLayout.createSequentialGroup()
                                    .addComponent(lbl_kdv)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_kdv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnl_urunBilgileriLayout.createSequentialGroup()
                                    .addComponent(lbl_marka)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cmb_marka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(pnl_urunBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_urunBilgileriLayout.createSequentialGroup()
                                .addComponent(lbl_urunBarkod)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_urunBarkod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_urunBilgileriLayout.createSequentialGroup()
                                .addGroup(pnl_urunBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_satisFiyat)
                                    .addComponent(lbl_kategori))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnl_urunBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_satisFiyat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmb_kategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addContainerGap(18, Short.MAX_VALUE)))
        );

        pnl_buton.setBackground(new java.awt.Color(255, 255, 255));

        btn_ekle.setText("Ekle");
        btn_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ekleActionPerformed(evt);
            }
        });

        btn_guncelle.setText("Güncelle");
        btn_guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guncelleActionPerformed(evt);
            }
        });

        btn_sil.setText("Sil");
        btn_sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_silActionPerformed(evt);
            }
        });

        lbl_urunId.setForeground(new java.awt.Color(255, 255, 255));
        lbl_urunId.setText("jLabel1");

        javax.swing.GroupLayout pnl_butonLayout = new javax.swing.GroupLayout(pnl_buton);
        pnl_buton.setLayout(pnl_butonLayout);
        pnl_butonLayout.setHorizontalGroup(
            pnl_butonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_butonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_ekle, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_guncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_sil, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_butonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_urunId)
                .addContainerGap())
        );
        pnl_butonLayout.setVerticalGroup(
            pnl_butonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_butonLayout.createSequentialGroup()
                .addComponent(lbl_urunId)
                .addGap(21, 21, 21)
                .addGroup(pnl_butonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ekle, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_guncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_sil, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnl_arkaLayout = new javax.swing.GroupLayout(pnl_arka);
        pnl_arka.setLayout(pnl_arkaLayout);
        pnl_arkaLayout.setHorizontalGroup(
            pnl_arkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnl_arkaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_arkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(pnl_arkaLayout.createSequentialGroup()
                        .addComponent(pnl_urunBilgileri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnl_buton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnl_arkaLayout.setVerticalGroup(
            pnl_arkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_arkaLayout.createSequentialGroup()
                .addComponent(pnl_header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_arkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_urunBilgileri, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnl_buton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_arka, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_arka, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_kategoriİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_kategoriİtemStateChanged
        // Seçilen değeri label'a aktarıyor.
        int kategori = KategoriController.kategoriIdBul(String.valueOf(cmb_kategori.getSelectedItem()));
        lbl_kategoriId.setText(String.valueOf(kategori));
    }//GEN-LAST:event_cmb_kategoriİtemStateChanged

    private void btn_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ekleActionPerformed
        if (txt_urunBarkod.getText().equals("") || txt_urunAdi.getText().equals("") || txt_stokAdet.getText().equals("") || txt_alisFiyat.getText().equals("") || txt_satisFiyat.getText().equals("") || txt_kdv.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Lütfen Tüm Alanları Doldurunuz!", "Bilgi", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        //Seçilen combobox'taki id'lere göre veritabanından bulunuyor.
        Kategoriler kategori = KategoriController.kategoriBul(Integer.valueOf(lbl_kategoriId.getText()));
        Markalar marka = MarkaController.markaBul(Integer.valueOf(lbl_markaId.getText()));

        // İlgili ürün veritabanına ekleniyor.
        try {
            UrunController.urunEkle(
                    txt_urunBarkod.getText(),
                    txt_urunAdi.getText(),
                    Integer.parseInt(txt_stokAdet.getText()),
                    Double.parseDouble(txt_alisFiyat.getText()),
                    Double.parseDouble(txt_satisFiyat.getText()),
                    Integer.parseInt(txt_kdv.getText()),
                    kategori,
                    marka);
            JOptionPane.showMessageDialog(null, "Yeni urun başarıyla eklendi.", "Bilgi", JOptionPane.INFORMATION_MESSAGE);
            temizle();
            tabloDoldur();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Bir hata oluştu. Tekrar deneyiniz.", "Hata", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_ekleActionPerformed

    private void cmb_markaİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_markaİtemStateChanged
        // Seçilen değeri label'a aktarıyor.
        int marka = MarkaController.markaIdBul(String.valueOf(cmb_marka.getSelectedItem()));
        lbl_markaId.setText(String.valueOf(marka));
    }//GEN-LAST:event_cmb_markaİtemStateChanged

    private void tbl_urunlerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_urunlerMouseClicked
        // Tablo üzerindeki ilgili satır seçildiğinde veriler kontrollere aktarılıyor
        lbl_urunId.setText(String.valueOf(tbl_urunler.getModel().getValueAt(tbl_urunler.getSelectedRow(), 0)));
        txt_urunBarkod.setText(String.valueOf(tbl_urunler.getModel().getValueAt(tbl_urunler.getSelectedRow(), 1)));
        txt_urunAdi.setText(String.valueOf(tbl_urunler.getModel().getValueAt(tbl_urunler.getSelectedRow(), 2)));
        txt_stokAdet.setText(String.valueOf(tbl_urunler.getModel().getValueAt(tbl_urunler.getSelectedRow(), 6)));
        txt_alisFiyat.setText(String.valueOf(tbl_urunler.getModel().getValueAt(tbl_urunler.getSelectedRow(), 7)));
        txt_satisFiyat.setText(String.valueOf(tbl_urunler.getModel().getValueAt(tbl_urunler.getSelectedRow(), 8)));
        txt_kdv.setText(String.valueOf(tbl_urunler.getModel().getValueAt(tbl_urunler.getSelectedRow(), 9)));
        txt_stokAdet.setEnabled(false);
    }//GEN-LAST:event_tbl_urunlerMouseClicked

    private void btn_silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_silActionPerformed
        // İlgili kontrolün boş olup olmadığı kontrol ediliyor.
        if (txt_urunBarkod.getText().equals("")) {
            JOptionPane.showConfirmDialog(null, "Silme yapabilmek için listeden bir kayıt seçiniz.", "Bilgi", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        // Confirmdialog ile onaya göre bilgileri veritabanında siliniyor.
        int secim = JOptionPane.showConfirmDialog(null, "Seçilen ürünü silmek istiyormusunuz?", "Uyarı", JOptionPane.WARNING_MESSAGE);
        if (secim == JOptionPane.YES_OPTION) {
            try {
                UrunController.urunSil(Integer.valueOf(lbl_urunId.getText()));
                JOptionPane.showMessageDialog(null, "Ürün başarıyla silindi.");
                temizle();
                tabloDoldur();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Bir hata oluştu. Tekrar deneyiniz.", "Hata", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_silActionPerformed

    private void btn_guncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guncelleActionPerformed
        // İlgili kontrolün boş olup olmadığı kontrol ediliyor.
        if (txt_urunBarkod.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Güncelleme yapabilmek için listeden bir kayıt seçiniz.", "Bilgi", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        //Seçilen combobox'taki id'lere göre veritabanından bulunuyor.
        Kategoriler kategori = KategoriController.kategoriBul(Integer.valueOf(lbl_kategoriId.getText()));
        Markalar marka = MarkaController.markaBul(Integer.valueOf(lbl_markaId.getText()));

        // Confirmdialog ile onaya göre bilgileri veritabanında güncelleniyor.
        int secim = JOptionPane.showConfirmDialog(null, "Seçilen ürünü güncellemek istiyormusunuz?", "Uyarı", JOptionPane.WARNING_MESSAGE);
        if (secim == JOptionPane.YES_OPTION) {
            try {
                UrunController.urunGuncelle(
                        Integer.parseInt(lbl_urunId.getText()),
                        txt_urunBarkod.getText(),
                        txt_urunAdi.getText(),
                        Integer.parseInt(txt_stokAdet.getText()),
                        Double.parseDouble(txt_alisFiyat.getText()),
                        Double.parseDouble(txt_satisFiyat.getText()),
                        Integer.parseInt(txt_kdv.getText()),
                        kategori,
                        marka);
                JOptionPane.showMessageDialog(null, "Ürün başarıyla güncellendi.");
                temizle();
                tabloDoldur();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Bir hata oluştu. Tekrar deneyiniz.", "Hata", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_guncelleActionPerformed

    // Textfieldlar için klavyeden veri girişi kontrolleri yapılıyor.
    private void txt_stokAdetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_stokAdetKeyPressed
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || (evt.getKeyChar() == KeyEvent.VK_BACK_SPACE) || (evt.getKeyChar() == KeyEvent.VK_DELETE)) {
            txt_stokAdet.setEditable(true);
        } else {
            txt_stokAdet.setEditable(false);
        }
    }//GEN-LAST:event_txt_stokAdetKeyPressed

    private void txt_alisFiyatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_alisFiyatKeyPressed
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || (evt.getKeyChar() == KeyEvent.VK_BACK_SPACE) || (evt.getKeyChar() == KeyEvent.VK_PERIOD) || (evt.getKeyChar() == KeyEvent.VK_DELETE)) {
            txt_alisFiyat.setEditable(true);
        } else {
            txt_alisFiyat.setEditable(false);
        }
    }//GEN-LAST:event_txt_alisFiyatKeyPressed

    private void txt_satisFiyatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_satisFiyatKeyPressed
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || (evt.getKeyChar() == KeyEvent.VK_BACK_SPACE) || (evt.getKeyChar() == KeyEvent.VK_PERIOD) || (evt.getKeyChar() == KeyEvent.VK_DELETE)) {
            txt_satisFiyat.setEditable(true);
        } else {
            txt_satisFiyat.setEditable(false);
        }
    }//GEN-LAST:event_txt_satisFiyatKeyPressed

    private void txt_kdvKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_kdvKeyPressed
        String value = txt_kdv.getText();
        int l = value.length();
        if ((l < 2) && (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') || (evt.getKeyChar() == KeyEvent.VK_BACK_SPACE) || (evt.getKeyChar() == KeyEvent.VK_DELETE)) {
            txt_kdv.setEditable(true);
        } else {
            txt_kdv.setEditable(false);
        }
    }//GEN-LAST:event_txt_kdvKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UrunIslemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UrunIslemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UrunIslemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UrunIslemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UrunIslemleri().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ekle;
    private javax.swing.JButton btn_guncelle;
    private javax.swing.JButton btn_sil;
    private javax.swing.JComboBox<String> cmb_kategori;
    private javax.swing.JComboBox<String> cmb_marka;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_alisFiyat;
    private javax.swing.JLabel lbl_kategori;
    private javax.swing.JLabel lbl_kategoriId;
    private javax.swing.JLabel lbl_kdv;
    private javax.swing.JLabel lbl_marka;
    private javax.swing.JLabel lbl_markaId;
    private javax.swing.JLabel lbl_satisFiyat;
    private javax.swing.JLabel lbl_stokAdet;
    private javax.swing.JLabel lbl_urunAdi;
    private javax.swing.JLabel lbl_urunBarkod;
    private javax.swing.JLabel lbl_urunId;
    private javax.swing.JPanel pnl_arka;
    private javax.swing.JPanel pnl_buton;
    private javax.swing.JPanel pnl_header;
    private javax.swing.JPanel pnl_urunBilgileri;
    private javax.swing.JTable tbl_urunler;
    private javax.swing.JTextField txt_alisFiyat;
    private javax.swing.JTextField txt_kdv;
    private javax.swing.JTextField txt_satisFiyat;
    private javax.swing.JTextField txt_stokAdet;
    private javax.swing.JTextField txt_urunAdi;
    private javax.swing.JTextField txt_urunBarkod;
    // End of variables declaration//GEN-END:variables
}
